--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-30-2020   
--------------------------------------------------------
DROP TABLE "SOAINT"."CLIENTE";
DROP TABLE "SOAINT"."DETALLEVENTA";
DROP TABLE "SOAINT"."PRODUCTO";
DROP TABLE "SOAINT"."VENTA";
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "SOAINT"."CLIENTE" 
   (	"IDCLIENTE" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"DNI" NUMBER, 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETALLEVENTA
--------------------------------------------------------

  CREATE TABLE "SOAINT"."DETALLEVENTA" 
   (	"IDDETALLEVENTA" NUMBER, 
	"IDVENTA" NUMBER, 
	"IDPRODUCTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "SOAINT"."PRODUCTO" 
   (	"IDPRODUCTO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"PRECIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "SOAINT"."VENTA" 
   (	"IDVENTA" NUMBER, 
	"IDCLIENTE" NUMBER, 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SOAINT.CLIENTE
SET DEFINE OFF;
REM INSERTING into SOAINT.DETALLEVENTA
SET DEFINE OFF;
REM INSERTING into SOAINT.PRODUCTO
SET DEFINE OFF;
Insert into SOAINT.PRODUCTO (IDPRODUCTO,NOMBRE,PRECIO) values ('1','prueba','23132');
REM INSERTING into SOAINT.VENTA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOAINT"."CLIENTE_PK" ON "SOAINT"."CLIENTE" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLEVENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOAINT"."DETALLEVENTA_PK" ON "SOAINT"."DETALLEVENTA" ("IDDETALLEVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOAINT"."PRODUCTO_PK" ON "SOAINT"."PRODUCTO" ("IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOAINT"."VENTA_PK" ON "SOAINT"."VENTA" ("IDVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SOAINT"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOAINT"."CLIENTE" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLEVENTA
--------------------------------------------------------

  ALTER TABLE "SOAINT"."DETALLEVENTA" ADD CONSTRAINT "DETALLEVENTA_PK" PRIMARY KEY ("IDDETALLEVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOAINT"."DETALLEVENTA" MODIFY ("IDDETALLEVENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "SOAINT"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOAINT"."PRODUCTO" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "SOAINT"."VENTA" ADD CONSTRAINT "VENTA_PK" PRIMARY KEY ("IDVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOAINT"."VENTA" MODIFY ("IDVENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DETALLEVENTA
--------------------------------------------------------

  ALTER TABLE "SOAINT"."DETALLEVENTA" ADD CONSTRAINT "FK_PRODUCTO" FOREIGN KEY ("IDPRODUCTO")
	  REFERENCES "SOAINT"."PRODUCTO" ("IDPRODUCTO") ENABLE;
  ALTER TABLE "SOAINT"."DETALLEVENTA" ADD CONSTRAINT "FK_VENTA" FOREIGN KEY ("IDVENTA")
	  REFERENCES "SOAINT"."VENTA" ("IDVENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "SOAINT"."VENTA" ADD CONSTRAINT "FK_CLIENTE" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "SOAINT"."CLIENTE" ("IDCLIENTE") ENABLE;





--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-30-2020   
--------------------------------------------------------
DROP SEQUENCE "SOAINT"."SQ_CLIENTE";
DROP SEQUENCE "SOAINT"."SQ_DETALLEVENTA";
DROP SEQUENCE "SOAINT"."SQ_PRODUCTO";
DROP SEQUENCE "SOAINT"."SQ_VENTA";
--------------------------------------------------------
--  DDL for Sequence SQ_CLIENTE
--------------------------------------------------------

   CREATE SEQUENCE  "SOAINT"."SQ_CLIENTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_DETALLEVENTA
--------------------------------------------------------

   CREATE SEQUENCE  "SOAINT"."SQ_DETALLEVENTA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PRODUCTO
--------------------------------------------------------

   CREATE SEQUENCE  "SOAINT"."SQ_PRODUCTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_VENTA
--------------------------------------------------------

   CREATE SEQUENCE  "SOAINT"."SQ_VENTA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

